### ISSUE TITLE
許可されていないメソッドを弾く

### ISSUE THREAD

**Issue by TetsuOtter** [TR-42/webserv#60]

**Comment by tatashir** [comment]
memo: routeconfigでつくったやつ

**Comment by TetsuOtter** [comment]
RouteConfig.Methodsがemptyであれば全許可、何か設定されていれば、そのメソッドだけを使用できる。

大文字かどうかはconfigを読んだ直後にチェックする (実装をこれからする) ので、気にしなくてOKです
